# Jumpsuit
- type: loadout
  id: HeadOfSecurityCommandJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommandHeadOfSecurity

# Neck
- type: loadout
  id: HeadOfSecurityRoyalCloak
  equipment:
    neck: ClothingNeckCloakRoyalHeadOfSecurity

# Pocket 2
- type: loadout
  id: SecurityGunVP78
  equipment:
    pocket2: WeaponPistolVP78
  storage:
    back:
    - MagazinePistol20
    - MagazinePistol20
